### ISSUE TITLE
How to create unit test in module?

### ISSUE THREAD

**Issue by ghost** [openedoo/openedoo#62]
I want to create unittest for my module database schema. this the folder structure,
```
├── module_employee
│   ├── database.py
│   ├── database.pyc
│   ├── datasmp.mwb
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── README.md
│   ├── requirement.json
│   └── tests
│       ├── __init__.py
│       ├── __init__.pyc
│       ├── test_database.py
│       └── test_database.pyc
```
This is the test code
```
import unittest

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from ..database import User


class User(unittest.TestCase):
    def setUp(self):
        host = 'mysql://root:asdzxcfv123@localhost:3306/db_openedoo'
        self.engine = create_engine(host)
        self.session = Session(engine)
        User.metada.create_all(self.engine)
        self.user = User(1, 'dwip', 'asdzxc', 'dwi purnomo', 12312312323123, '', '', '', '', 'guru')
        self.session.add(self.user)
        self.session.commit()

    def tearDown(self):
        User.metadata.drop_all(self.engine)

    def test_query_user(self):
        expected = [self.user]
        result = self.session.query(User).all()
        self.assertEqual(result, expected)
```
when i run `python -m unittest` inside the `module_employee` and the `openeedo` root folder i get `Ran 0 tests in 0.000s OK`, when i run `python -m unittest discover -t .` insede `openedoo` root folder, i get:
```
E
======================================================================
ERROR: modules.module_employee.tests.test_database (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: modules.module_employee.tests.test_database
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/dwi/kerja/venv2/openedoo/modules/module_employee/__init__.py", line 1, in <module>
    from openedoo.core.libs import blueprint
  File "/home/dwi/kerja/venv2/openedoo/openedoo/__init__.py", line 39, in <module>
    import route
  File "/home/dwi/kerja/venv2/openedoo/openedoo/route.py", line 15, in <module>
    from modules.module_employee import module_employee
ImportError: cannot import name module_employee


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
i don't know what to do, help me create unittest please.

**Comment by rendiya** [comment]
Close temporary
