### ISSUE TITLE
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.

### ISSUE THREAD

**Issue by rendiya** [openedoo/openedoo#79]
insert db with error but its insert in database

in function Query().raw()

error raise
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    print registration(data)
  File "/home/rendiya/pypro/aksaramaya/mocostore/model/openedoo-orm/module/users.py", line 35, in registration
    print query.raw(query_registration)
  File "/home/rendiya/pypro/aksaramaya/mocostore/model/openedoo-orm/db/__init__.py", line 134, in raw
    for value in result:
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 871, in __iter__
    row = self.fetchone()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 1184, in fetchone
    self.cursor, self.context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1396, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 1175, in fetchone
    row = self._fetchone_impl()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 1058, in _fetchone_impl
    return self._non_result(None)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/result.py", line 1078, in _non_result
    "This result object does not return rows. "

**Comment by ghost** [comment]
it affected me too, what is the solution?

**Comment by ghost** [comment]
according to http://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.ResultProxy.
i've made a safety check to handle query that doesn't returns row, like in the operation of insert, update.
```
    res = connection.execute(query)
    if res.returns_rows:
        # use special handler for dates and decimals
        return json.dumps([dict(r) for r in res], default=alchemyencoder,encoding='latin-1  ')
    return res
```
i'd love to know the better way.

**Comment by jkryanchou** [comment]
Is there any good solution on preventing it been closed automatically? Or just get the 0 rows.

**Comment by rendiya** [comment]
yes this is for return []

**Comment by jkryanchou** [comment]
@rendiya So the answer above was the right way to figure this out?
